### ISSUE TITLE
State of bugs and things to improve

### ISSUE THREAD

**Issue by GMDIV** [brianboyko/canyouhearusis#3]
- There is a random white flash that seems to randomly happen upon background image change. 
- We need the currency state to change with the language state, so that when they click on a new language, the currency will generally match it. Things to think about with that would be how to deal with english countries with non US currencies. 
- In regards to the previous, we would need a currency button for each acceptable currency on the donate div/screen. In this case, we can let them switch currency in case they prefer US dollars while being from Iceland, or if we use US dollars as the default for english, though they are from england and they use the Pound. 
- Make sure that the custom amount is sanitized. As of right now, I can put $0000.00009 as an amount and it lets me go to the credit card input screen. I can also put $0000.-00009 and it will let that go through as well. Or even lkjlakfjlds;f++==!
- A credit card checker would be nice, which would display the logo of the type of card they are using as they are putting it in. Also, if it isn't in there already, sanitize those inputs as well and make sure that it blocks it if it doesn't have the right amount. Keep in mind that American express might have a different number of digits, so it might not always be 16. (maybe)
- It would be good to have a link on the donate page, saying Powered By Stripe (learn more) or something like that which they could click on to see that what they are putting their information through is legit. They need to know everything is protected without a secure login...if it is.
- The twitter and facebook share pages look a bit sketchy as they take you to a lone posting page, rather than autofilling a post within the main feed page.
- It would be good for the learn page to be restructured in order to decrease the amount being loaded. I'd suggest something like one main video player that is set to the first link by default. Then there is a list of each of those links in an accordion structure, pulling down the information when clicked and setting the main video to the one connected with that div's information.

**Comment by kerryboyko** [comment]
Moved these into seperate bug reports.
